language: node_js

node_js:
  - "node"

stages:
  - test
  - build
  - name: next
    if: branch = next
  - name: coveralls
    if: branch = master
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build
      script: yarn transpile
    - stage: next
      deploy:
        provider: npm
        email: "chafiliny@gmail.com"
        api_key: $NPM_API_KEY
        tag: next
    - stage: coveralls
      script: yarn coveralls
    - stage: publish
      deploy:
        provider: npm
        email: "chafiliny@gmail.com"
        api_key: $NPM_API_KEY
