language: node_js

node_js:
  - "node"

script: yarn test

deploy:
  skip_cleanup: true
  provider: script
  script: yarn coveralls
  on:
    branch: master
  provider: script
  script: yarn transpile
  on:
    branches:
      only:
      - master
      - next
  skip_cleanup: true
  provider: npm
  email: "chafiliny@gmail.com"
  api_key: $NPM_API_KEY
  tag: next
  on:
    branch: next
  provider: npm
  email: "chafiliny@gmail.com"
  api_key: $NPM_API_KEY
  on:
    branch: master

