language: node_js

node_js:
  - "node"

jobs:
  include:
    - stage: test
      script:
      - yarn test
      - yarn coveralls
    - stage: npm release
      deploy:
        provider: npm
        email: "chafiliny@gmail.com"
        api_key: $NPM_API_KEY
        on:
          branch: master

