language: node_js
node_js:
- node

before_deploy: 'yarn coveralls'

deploy:
  provider: npm
  email: chafiliny@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: chafilin/connected-react-socket
