language: node_js

node_js:
  - "node"

script:
  - yarn test

jobs:
  include:
    - stage: npm release
      script: yarn coveralls
      script: npm publish
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: master

