language: node_js
node_js:
- node

script: yarn build

after_success: yarn test

before_deploy: 'yarn build'

deploy:
  skip_cleanup: true
  provider: npm
  email: chafiliny@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: chafilin/connected-react-socket

after_deploy: 'yarn coveralls'
